蹲饼配置接口
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #107
Opened 2022-12-17 14:05 UTC by phidiaLam

2022-12-17 14:27 UTC, YoungHector approved these changes
只能看懂表结构，应该没啥问题。

2022-12-17 14:30 UTC, YoungHector approved these changes

2023-01-01 13:08 UTC, Goodjooy requested changes

2023-01-01 13:08 UTC, Goodjooy commented on src/router/back_end/fetcher/mod.rs
> +        )
接口较多，建议通过功能进行进一步分类

2023-01-01 13:08 UTC, Goodjooy commented on src/serves/backend/fetcher/fetcher_configs/controllers.rs
> +        MapReject(platform): MapReject<
模式匹配可以更进一步，直接拿 `type_id`

2023-01-01 13:08 UTC, Goodjooy commented on src/serves/backend/fetcher/platform_configs/controllers.rs
> +            // 异步获取
```suggestion
            // 并发执行
```

2023-01-01 13:08 UTC, Goodjooy commented on logic/fetcher_logic/src/implement.rs
> +}
单源代码文件大小控制在150~200 行左右

2023-01-01 13:11 UTC, phidiaLam commented on global/redis_global/src/redis_key/fetcher.rs
> +    "cookie:fetcher:config:live:number"; // 至今蹲饼器存活的最大数量
这边想的是已经有文件区分了就不再套一层结构体了，用的时候还是比较长的，文件区分就看redis_key::fetcher::key用 这样子就知道这个是一个redis的可以并且用在蹲饼器的。再分感觉有点多余

2023-01-01 13:14 UTC, phidiaLam commented on libs/checker/src/require_check.rs
> +
可以的 到时候合并时候搞吧

2023-01-01 13:14 UTC, phidiaLam commented on models/sql-models/src/fetcher/config/checkers/mod.rs
> +    HasRem(#[from] HasRemError<1000>),
好

2023-01-01 13:14 UTC, phidiaLam commented on models/sql-models/src/fetcher/config/models/model_config.rs
> +    pub interval_by_time_range: Option<String>, // 组内蹲饼时间段间隔
噢噢 文档注释有这种用 我到时候全局改一下

2023-01-01 13:15 UTC, phidiaLam commented on models/sql-models/src/fetcher/config/operate/create.rs
> +        });
好

2023-01-01 13:15 UTC, Goodjooy commented on global/redis_global/src/redis_key/fetcher.rs
> +    "cookie:fetcher:config:live:number"; // 至今蹲饼器存活的最大数量
混在use 里面谁看得见（）

2023-01-01 13:20 UTC, phidiaLam commented on models/sql-models/src/fetcher/config/checkers/mod.rs
> +    HasRem(#[from] HasRemError<1000>),
好

2023-01-01 13:22 UTC, phidiaLam commented on logic/fetcher_logic/src/implement.rs
> +}
逻辑层不用吧 你这分文件下去又会乱乱的 本身逻辑层就是在把大量信息整合

2023-01-01 13:25 UTC, Goodjooy commented on logic/fetcher_logic/src/implement.rs
> +}
这不是全部糊一起的理由

2023-01-01 13:26 UTC, phidiaLam commented on logic/fetcher_logic/src/implement.rs
> +}
那要怎么拆分

2023-01-01 13:34 UTC, phidiaLam commented on global/redis_global/src/redis_key/fetcher.rs
> +    "cookie:fetcher:config:live:number"; // 至今蹲饼器存活的最大数量
我本来是不混use呀 就只use redis_key

2023-01-02 08:45 UTC, phidiaLam commented on models/sql-models/src/fetcher/datasource_config/operate/create.rs
> +                .expect_or_log("config为非法json格式"),
这是什么意思

2023-01-02 08:46 UTC, phidiaLam commented on models/sql-models/src/fetcher/datasource_config/operate/retrieve.rs
> +}
find_datasource_list_by_page_size 没有说明什么呀

2023-01-02 11:38 UTC, phidiaLam commented on models/sql-models/src/fetcher/datasource_config/operate/retrieve.rs
> +        datasource: Option<String>,
这个感觉挺合理 就不改啦

2023-01-06 09:11 UTC, Goodjooy requested changes

2023-01-06 09:11 UTC, Goodjooy commented on models/sql-models/src/fetcher/platform_config/operate/update.rs
> +    pub async fn update_platform_config<'db, D>(
函数名冗余？

2023-01-06 09:11 UTC, Goodjooy commented on models/sql-models/src/fetcher/platform_config/operate/verify.rs
> +    }
为什么下面的不用上面的？

2023-01-06 09:11 UTC, Goodjooy commented on models/sql-models/src/fetcher/platform_config/operate/verify.rs
> +    pub async fn has_datasource_with_id(
函数名好怪，但是我不好说

2023-01-14 09:22 UTC, phidiaLam commented on models/sql-models/src/fetcher/config/checkers/config_data.rs
> +}
以前不是都放在这边吗，可以intoActiveModel

2023-01-14 09:22 UTC, phidiaLam commented on models/sql-models/src/fetcher/config/operate/create.rs
> +    pub async fn create_configs_by_platform<'db, D>(
可以

2023-01-20 00:35 UTC, Goodjooy approved these changes

2023-01-20 15:51 UTC, merged