用户操作接口
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #119
Opened 2023-02-15 07:59 UTC by phidiaLam

2023-02-15 09:35 UTC, Goodjooy commented
我记得有说这个operate 独立一个crate 吧（）

2023-02-28 16:02 UTC, Goodjooy requested changes

2023-02-28 16:02 UTC, Goodjooy commented on models/sql-models/src/fetcher/datasource_config/operate/verify.rs
> +        let first = Func::cust(UuidToBin).arg(first.hyphenated().to_string());
这里不需要 `to_string` 获得所有权吧？ 可以传递 `&[u8]`, `&str` ,`&String`

2023-02-28 16:04 UTC, phidiaLam commented on logic/ceobe_user_logic/src/implements.rs
> +        // 判断用户是否存在
这边写成中间件吧，看哪个接口要挂载，很多地方都要用

2023-02-28 16:06 UTC, phidiaLam commented on models/ceobe-user/src/lib.rs
> +}
这边什么意思 没有很懂

2023-03-01 10:30 UTC, phidiaLam commented on libs/mysql_func/Cargo.toml
> +sea-query = { workspace = true }
那我这边不是还得引入sql_connection

2023-03-01 15:18 UTC, phidiaLam commented on models/ceobe-user/src/mongo/user/create.rs
> +        )
下面那个return的返回要怎么办

2023-03-01 17:05 UTC, phidiaLam commented on models/sql-models/src/fetcher/datasource_config/operate/verify.rs
> +        let first = Func::cust(UuidToBin).arg(first.hyphenated().to_string());
不转成string要传什么，我试了一下好像只能to_string

2023-03-05 09:53 UTC, phidiaLam commented
@Goodjooy 好啦

2023-03-05 12:12 UTC, Goodjooy approved these changes

2023-03-05 12:51 UTC, phidiaLam commented
@Goodjooy OK

2023-03-05 17:21 UTC, merged