datasource删除改用软删除
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #120
Opened 2023-02-17 16:27 UTC by phidiaLam

2023-02-28 16:12 UTC, Goodjooy requested changes

2023-02-28 16:12 UTC, Goodjooy commented on migrate/sql-migration/src/fetcher_datasource_config/m20230217_135012_add_sort_detele.rs
> +                Value::ChronoDateTime(Box::new(get_zero_data_time()).into()),
什么原始写法
https://docs.rs/sea-query/latest/sea_query/value/enum.Value.html#impl-From%3CNaiveDateTime%3E-for-Value
https://docs.rs/sea-query/latest/sea_query/expr/enum.SimpleExpr.html#method.ne
https://docs.rs/sea-query/latest/sea_query/expr/enum.SimpleExpr.html#impl-From%3CT%3E-for-SimpleExpr

2023-02-28 16:12 UTC, Goodjooy commented on models/sql-models/src/fetcher/datasource_config/checkers/datasource_config_data.rs
> +    ) -> ActiveModel {
这个变成类似于 `update_by` 之类的trait 如何？

2023-02-28 16:12 UTC, Goodjooy commented on models/sql-models/src/fetcher/datasource_config/models/model_datasource_config.rs
> +}
软删除的整合成trait 是否可行？
这样全部软删除功能可以使用统一接口

2023-02-28 16:12 UTC, Goodjooy commented on models/sql-models/src/fetcher/datasource_config/checkers/datasource_config_data.rs
> +    ) -> ActiveModel {
这个函数名称还有些迷惑

2023-02-28 16:12 UTC, Goodjooy commented on models/sql-models/src/fetcher/datasource_config/checkers/datasource_config_data.rs
> +    ) -> ActiveModel {
recover and update?

2023-02-28 16:12 UTC, Goodjooy commented on models/sql-models/src/fetcher/datasource_config/operate/mod.rs
> +        resp_msg = "蹲饼器数据源不存在"
数据源不存在

2023-02-28 16:12 UTC, Goodjooy commented on models/sql-models/src/fetcher/datasource_config/operate/mod.rs
>  #[allow(dead_code)]
这个应该去掉了吧？

2023-03-01 09:48 UTC, phidiaLam commented on models/sql-models/src/fetcher/datasource_config/checkers/datasource_config_data.rs
> +    ) -> ActiveModel {
这个我把命名改了

2023-03-03 14:32 UTC, Goodjooy approved these changes

2023-03-03 14:33 UTC, merged