饼临时主列表
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #124
Opened 2023-03-12 14:06 UTC by phidiaLam

2023-03-13 14:46 UTC, Goodjooy requested changes

2023-03-13 14:46 UTC, Goodjooy commented on dao/ceobe-cookie/src/mongo/temp_list/retrieve.rs
> +                        .limit(page_number)
你是用 ObjectId 来排序的吗？
ObjectId 不保证有序啊
以及，first Id 为什么不直接给 objectId?

2023-03-13 14:46 UTC, Goodjooy commented on dao/ceobe-cookie/src/mongo/temp_list/retrieve.rs
> +    }
这个接口有什么特殊使用要返回String 吗？

2023-03-13 14:46 UTC, Goodjooy commented on dao/fetcher/src/sql/datasource_combination/retrieve.rs
> +            _ => return Err(OperateError::LargeThen256),
这里推荐使用query builder

2023-03-13 14:46 UTC, Goodjooy commented on dao/fetcher/src/sql/datasource_combination/retrieve.rs
> +        db: &impl ConnectionTrait, datasource_id: i32,
not_db 是什么意思？
我写的这种接口一般叫raw

2023-03-13 14:46 UTC, Goodjooy commented on libs/bitmap-convert/src/base70.rs
> +    fn base_70_to(string: String) -> Result<Self, Self::Error>
from_base_70 推荐叫这个

2023-03-13 14:46 UTC, Goodjooy commented on libs/bitmap-convert/src/base70.rs
> +        let mut result: Vec<char> = Vec::new();
可以考虑进行内存预分配或者扩容，具体参考vec 文档

2023-03-13 14:46 UTC, Goodjooy commented on libs/bitmap-convert/src/base70.rs
> +        Ok(result.into_iter().collect())
这边可以直接用迭代器collect 吧
```suggestion
        // 转换为70进制的字符数组
        let s = bytes.into_iter().map(|b|index_to_char[b as usize])
        .collect()
        Ok(v)
```
顺便一提，String 应该可以直接从Vec 转换

2023-03-13 14:46 UTC, Goodjooy commented on libs/bitmap-convert/src/vec_i32.rs
> +    fn bitmap_to_i32(&self) -> Vec<i32>;
理论上应该返回 Vec<usize>

2023-03-13 14:46 UTC, Goodjooy commented on libs/qiniu-manager/src/manager/mod.rs
> +            Some(dir) => dir.to_owned() + "/" + self.file_name(),
用format!
```suggestion
            Some(dir) =>format!("{}/{}", dir.to_owned() , self.file_name()),
```
其实更好是用join,但是那个出来的是 OsStr 比较麻烦

2023-03-13 14:46 UTC, Goodjooy commented on logic/ceobe_user_logic/src/implements.rs
> +        };
这个为什么不直接维持一个 [u64;4]?

2023-03-13 14:49 UTC, phidiaLam commented on dao/ceobe-cookie/src/mongo/temp_list/retrieve.rs
> +                        .limit(page_number)
ObjectId保证有序，First_Id是什么？

2023-03-13 15:10 UTC, phidiaLam commented on dao/fetcher/src/sql/datasource_combination/create.rs
> +            datasourceCombCreate.bitmap4 = comb_id_info.bitmap1,
麻了

2023-03-13 16:55 UTC, phidiaLam commented on dao/ceobe-cookie/src/mongo/temp_list/retrieve.rs
> +    }
你的意思是返回ObjectId类型？

2023-03-23 12:20 UTC, Goodjooy requested changes

2023-03-23 12:20 UTC, Goodjooy commented on models/sql-models/src/fetcher/datasource_combination/models/model_datasource_combination.rs
> +        ActiveModel {
let [bitmat1,bitmat2,bitmap3,bitmap4] = bitmaps;

2023-03-26 10:34 UTC, phidiaLam commented on dao/fetcher/src/sql/datasource_combination/create.rs
> +            datasourceCombCreate.bitmap4 = bitmaps[3],
这边感觉还是直接十进制数字好，不会太多01容易输错。

2023-03-28 00:43 UTC, Goodjooy approved these changes

2023-03-28 00:43 UTC, merged