将mob push 合并内主项目
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #125
Opened 2023-03-21 10:02 UTC by Goodjooy

- [ ] 合并进主项目
  - [ ] 使用 general-request-client
  - [ ] 去除subscribe 相关trait
  - [ ] 调整error 内容
- [ ] 提供可用接口
- [ ] `mob_push` 提供 `MobPushManager`, `users`, `content` 即可发起一次mob push , 自动 分批，自动限流
- [ ] `MobPushPrepare` 初始化相关配置

2023-03-23 13:37 UTC, phidiaLam requested changes

2023-03-23 13:37 UTC, phidiaLam commented on middle-server/mob-push-server/src/push_forward.rs
> +}
这四个不然注释标注一下吧

2023-03-23 13:54 UTC, Goodjooy commented on middle-server/mob-push-server/src/push_notify/android/image.rs
> +    /// - OPPO厂商大图需要申请权限，否则会报错导致客户端收不到推送消息
额，我测试是可以推送的啊
没上架商城也能搞推送吧？

2023-03-23 13:54 UTC, Goodjooy commented on middle-server/mob-push-server/src/push_forward.rs
> +}
没事，我也不知道是什么意思

2023-03-27 10:37 UTC, phidiaLam commented on middle-server/mob-push-server/src/push_notify/android/image.rs
> +    /// - OPPO厂商大图需要申请权限，否则会报错导致客户端收不到推送消息
大图推送也可以吗，那这边说oppo要申请是？

2023-03-28 00:48 UTC, Goodjooy commented on middle-server/mob-push-server/src/push_notify/android/image.rs
> +    /// - OPPO厂商大图需要申请权限，否则会报错导致客户端收不到推送消息
啊是oppo 啊，那不清楚。
申请可能是程序权限申请？

2023-03-28 05:37 UTC, phidiaLam approved these changes

2023-03-28 05:37 UTC, merged