🐛 修复请求调度器路径错误
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #132
Opened 2023-05-06 09:30 UTC by phidiaLam

2023-05-13 16:21 UTC, Goodjooy requested changes

2023-05-13 16:21 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +        let newest_cookies = new_cookies.clone().into_iter().last().unwrap();
这里建议直接将newest_cookie_id 拿出来,ObjectId 本身是实现了Copy的
当前写法会拷贝整个序列

2023-05-13 16:21 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/main_list.rs
> +                ))
涉及字符串拼接的，建议提供一个函数用于此操作而不是每次都拉一次

2023-05-13 16:21 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/view.rs
> +
改为 空字符串序列化为None

2023-05-13 16:21 UTC, Goodjooy commented on service/qiniu_service/src/impletements/datasource_comb.rs
> +            None => {
这里可以不用使用match, 只要进入Some() 就会直接返回，后续代码都不会执行

2023-05-13 16:21 UTC, Goodjooy commented on service/qiniu_service/src/impletements/datasource_comb.rs
> +                            ),
涉及拼接的建议提供函数接口使用

2023-05-13 16:21 UTC, Goodjooy commented on service/qiniu_service/src/impletements/datasource_comb.rs
> +        update_cookie_id: Option<String>, comb_id: String,
cookie_id? 饼id ？还是 latest_cookie_id?
update_cookie_id? 更新饼id？ 还是 latest_updated_cookie_id?

2023-05-13 16:21 UTC, Goodjooy commented on global/redis_global/src/redis_key/cookie_list.rs
> +    pub const NEW_UPDATE_COOKIE_ID: &str = "cookie:list:new:update:id:";
文档注释，文档注释

2023-05-13 16:21 UTC, Goodjooy commented on service/qiniu_service/src/model.rs
> +    pub update_cookie_id: Option<String>,
建议改成使用& ‘s str 
只有序列化要求

2023-05-13 16:22 UTC, Goodjooy commented on service/qiniu_service/src/model.rs
> +    pub update_cookie_id: Option<String>,
对了，这里也是普通注释不是文档注释

2023-05-13 16:26 UTC, phidiaLam commented on logic/ceobe_cookie_logic/src/error.rs
> +    UpdateCookieCacheExpire(String),
这个匹配的吧？更新饼id是个名词，不是 更新 饼id

2023-05-13 16:27 UTC, phidiaLam commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +        let newest_cookies = new_cookies.clone().into_iter().last().unwrap();
是直接后面链式.cookie_id这样子拿出来吗

2023-05-13 16:28 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/error.rs
> +    UpdateCookieCacheExpire(String),
UpdateCookieIdCacheFailure? expire 是超时了吧？

2023-05-13 16:30 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +        let newest_cookies = new_cookies.clone().into_iter().last().unwrap();
1. 去掉clone
2. 是用`Option::map` 拿，这里使用某些特定类型的数据结构也许会更好

2023-05-13 16:48 UTC, phidiaLam commented on service/qiniu_service/src/impletements/datasource_comb.rs
> +            None => {
不过我这个也没有后续代码了呀

2023-05-13 17:25 UTC, phidiaLam commented on service/qiniu_service/src/impletements/datasource_comb.rs
> +        update_cookie_id: Option<String>, comb_id: String,
饼id和更新饼id 没问题呀

2023-05-14 08:42 UTC, Goodjooy requested changes

2023-05-14 08:42 UTC, Goodjooy commented on service/qiniu_service/src/impletements/datasource_comb.rs
> +            None => {
但是去掉match 可以少一层缩进啊

2023-05-14 08:42 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +                &new_cookies.first().unwrap().source.unique,
关于unwrap, 我的观点是不能保证为长度不为0的vec
可以考虑添加类型来限制，比如

```rust
struct MinSizeVec<const N: usize, T> {
    base: [T; N],
    residual: Vec<T>,
}

impl<const N: usize, T> MinSizeVec<N, T> {
    fn last(&self) -> &T {
        if let Some(last) = self.residual.last() {
            last
        } else {
            &self.base[N - 1]
        }
    }
}

impl<const N: usize, T> TryFrom<Vec<T>> for MinSizeVec<N, T> {
    type Error = Vec<T>;

    fn try_from(value: Vec<T>) -> Result<Self, Self::Error> {
        if N == 0 {
            panic!("the N should not be 0");
        }
        if value.len() < N {
            Err(value)
        } else {
            let mut base = value;
            let residual = base.split_off(N);
            let base = unsafe { base.try_into().unwrap_unchecked() };

            Ok(Self { base, residual })
        }
    }
}
```
可以保证传入类型有至少N长度的元素

2023-05-14 08:42 UTC, Goodjooy commented on service/qiniu_service/src/model.rs
> +    pub update_cookie_id: Option<&'s str>,
不如再加个Copy?

2023-05-14 09:49 UTC, phidiaLam commented on global/redis_global/src/redis_key/mod.rs
> +}
key也要display吧

2023-05-14 14:10 UTC, Goodjooy approved these changes

2023-05-14 14:11 UTC, Goodjooy approved these changes

2023-05-14 14:19 UTC, merged