数据源列表获取数据源组合id接口
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #135
Opened 2023-05-27 07:19 UTC by phidiaLam

2023-05-30 09:58 UTC, Goodjooy requested changes

2023-05-30 11:04 UTC, phidiaLam commented on logic/ceobe_user_logic/src/implements.rs
> +    async fn remove_delete_datasource_upload_cdn(
确实

2023-05-31 00:32 UTC, Goodjooy commented on logic/ceobe_user_logic/src/implements.rs
> +            task::yield_now().await;
就算下次使用数据库时数据还没写入也是预期的吗？

2023-05-31 02:16 UTC, phidiaLam commented on logic/ceobe_user_logic/src/implements.rs
> +            task::yield_now().await;
就算一直没写入都符合预期

2023-06-09 14:33 UTC, merged