数据源新增跳转url
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #136
Opened 2023-05-28 03:46 UTC by phidiaLam

2023-05-30 10:02 UTC, Goodjooy requested changes

2023-05-30 10:02 UTC, Goodjooy commented on logic/fetcher_logic/src/view.rs
> +    pub jump_url: Option<String>,
这里不直接使用 `url::Url`吗？ 那个有提供序列化和反序列化的

2023-05-30 11:01 UTC, phidiaLam commented on logic/fetcher_logic/src/view.rs
> +    pub jump_url: Option<String>,
那avatar也一起改一下咯？

2023-05-31 00:25 UTC, Goodjooy approved these changes

2023-05-31 00:25 UTC, Goodjooy commented on logic/fetcher_logic/src/view.rs
> +    pub jump_url: Option<String>,
那也行吧

2023-05-31 02:15 UTC, merged