漫画页接口实现
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #137
Opened 2023-05-29 10:16 UTC by phidiaLam

2023-05-30 09:50 UTC, Goodjooy requested changes

2023-05-30 09:50 UTC, Goodjooy commented on models/mongo-models/src/ceobe/cookie/terra_comic/models/mod.rs
> +}
关于这种有个ID, 有个body 的， 有没有一些统一的想法？

比如这样？
```rust
struct WithId<Id, T>{
    id:Id,
    #[serde(flatten)]
    payload:T
}
```

2023-05-30 09:50 UTC, Goodjooy commented on migrate/mongo-migration/src/migrations/ceobe/cookie/terra_comic.rs
> +    }
这边comic Id 不加个unique 约束？

2023-05-30 09:50 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/view.rs
> +    /// 改漫画基础信息
该

2023-05-30 10:51 UTC, phidiaLam commented on models/mongo-models/src/ceobe/cookie/terra_comic/models/mod.rs
> +}
我觉得默认的_id可以这样子，这种必要性不大，这种还是原本信息

2023-05-30 10:52 UTC, phidiaLam commented on migrate/mongo-migration/src/migrations/ceobe/cookie/terra_comic.rs
> +    }
这个其实_id也是这个字段，只是方便看，分析器入库多个cid字段，不过加个unique也行

2023-05-31 00:29 UTC, Goodjooy commented on models/mongo-models/src/ceobe/cookie/terra_comic/models/mod.rs
> +}
也行，我是觉得每个类型都搞个sub model 然后单独去掉id 感觉有点繁琐

2023-05-31 00:30 UTC, Goodjooy approved these changes

2023-05-31 02:04 UTC, merged