Feat 新最新饼id逻辑
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #175
Opened 2024-04-09 17:54 UTC by phidiaLam

2024-04-10 00:54 UTC, Goodjooy requested changes

2024-04-10 00:54 UTC, Goodjooy commented on global/redis_global/src/redis_key/cookie_list.rs
> +    #[allow(deprecated)]
`#[allow(deprecated)]` 是因为挂载deprecated 的函数里面可能使用的其他deprecated接口，因此添加的，这里符合这个情况吗？

2024-04-10 00:54 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/main_list.rs
> +        }
这里的`from_str` 不能辅助类型推导吗？

2024-04-10 00:54 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/main_list.rs
> +    ) -> LogicResult<CombIdToCookieIdReq> {
返回类型叫 Req?
类型名怪怪的，混合ID转饼ID请求？

2024-04-10 00:54 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +            DatasourceCombinationOperate::find_comb_id_by_one_datasource_raw(
一行高达77个字符，这再不简化一行要放不下了

2024-04-10 00:54 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +    ///         - 如果存在，需要判断当前饼id和数据库里饼id那个大。接口cookie_id要取大的那个（最新）【这边没办法批量操作的原因就是因为每个得单独判断，每个下面数据源是不一样的】
```suggestion
    ///         - 如果存在，取当前饼id和数据库里饼id较大的为cookie_id。【这边没办法批量操作的原因就是因为每个得单独判断，每个下面数据源是不一样的】
```

2024-04-10 00:54 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +                        last_comb_info.cookie_id.unwrap().parse()?;
既然保证非Null, 那为何不用不带None 的结构体来反序列化？

2024-04-10 00:54 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +                        last_comb_info.cookie_id.unwrap().parse()?;
既然保证非Null, 那为何不用不带None 的结构体来反序列化？

2024-04-10 00:54 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +        futures::future::join_all(handles).await;
如果要`join_all` 使用 `tokio::spawn` 不是必须的

2024-04-10 00:54 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +                if update_id.to_string() != update_cookie {
感觉`ObjectId` 专门准备一个包装类型可能更好，例如`CookieId(pub ObjectId)` 然后为其实现 [FromRedisValue](https://docs.rs/redis/latest/redis/trait.FromRedisValue.html#),[ToRedisArgs](https://docs.rs/redis/latest/redis/trait.ToRedisArgs.html#) 和辅助的 `Eq` 等

2024-04-10 00:54 UTC, Goodjooy commented on logic/ceobe_cookie_logic/src/view.rs
> +pub struct CombIdToCookieIdReq {
类型名有点意义不明

2024-04-10 00:54 UTC, Goodjooy commented on logic/ceobe_user_logic/src/view.rs
> +pub struct CombIdToCookieIdReq {
怎么第二次见到这个类型名了？

2024-04-10 00:54 UTC, Goodjooy commented on src/serves/qiniu_cdn/datasource/comb/controllers.rs
> +        >,
这里如果Path解析错误会返回RespResult 的错误响应

2024-04-10 00:54 UTC, Goodjooy commented on src/serves/qiniu_cdn/datasource/comb/controllers.rs
> +            Err(_) => (StatusCode::from_u16(500).unwrap(), None.into()),
```suggestion
            Err(_) => (StatusCode::INTERNAL_SERVER_ERROR, None.into()),
```

[INTERNAL_SERVER_ERROR](https://docs.rs/http/latest/http/status/struct.StatusCode.html#associatedconstant.INTERNAL_SERVER_ERROR)

2024-04-10 01:10 UTC, phidiaLam commented on src/serves/qiniu_cdn/datasource/comb/controllers.rs
> +        >,
没什么关系？错误只要有错误码就可以？不过如果要统一的话怎么改好

2024-04-10 01:12 UTC, phidiaLam commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +                        last_comb_info.cookie_id.unwrap().parse()?;
因为和返回共用一个结构体，返回那边是可能为None

2024-04-10 01:34 UTC, Goodjooy commented on logic/ceobe_user_logic/src/view.rs
> +pub struct CombIdToCookieIdReq {
这种一样的东西我感觉可以往上提，有一模一样的重复的结构体如果需要修改会比较麻烦

2024-04-10 01:35 UTC, Goodjooy commented on src/serves/qiniu_cdn/datasource/comb/controllers.rs
> +        >,
如果要处理，那参数类型要改成 `Result<Path<String>,PathRejection>`

2024-04-10 01:37 UTC, phidiaLam commented on logic/ceobe_user_logic/src/view.rs
> +pub struct CombIdToCookieIdReq {
但是我们没有dao层，总不能塞别人家里吧

2024-04-10 10:15 UTC, Goodjooy requested changes

2024-04-10 10:15 UTC, Goodjooy commented on src/serves/qiniu_cdn/datasource/comb/controllers.rs
> +            Err(_) => (StatusCode::INTERNAL_SERVER_ERROR, None.into()),
这里是输入有问题， 应该400 BAD_REQUEST

2024-04-10 11:31 UTC, HessTina-YuI commented on logic/ceobe_cookie_logic/src/impletements/new_cookie.rs
> +            let cookie_id = if let (Some(mut newest_cookie_id), true) = (
cookie_id 可以换个名字，虽然 if let 会重新赋值类型，如果没有编译器提示，会有误导性，与入参做区分

2024-04-10 11:31 UTC, HessTina-YuI commented on logic/ceobe_user_logic/src/implements.rs
> +        db: SqlDatabaseOperate, mut redis_client: RedisConnect,
这里操作 redis 连接池，需要可变参数么？

2024-04-10 14:26 UTC, phidiaLam commented
> @phidiaLam CombIdToCookieId 那个是不是也可以用CookieID?

我的意见还是保留，这个是通过combid查最新cookieid的

2024-04-10 14:50 UTC, Goodjooy commented
> > @phidiaLam CombIdToCookieId 那个是不是也可以用CookieID?
> 
> 我的意见还是保留，这个是通过combid查最新cookieid的

额？为什么呢？都是ObjectId 吧？
`type CombId = CookieId`

2024-04-10 15:44 UTC, phidiaLam commented
> > > @phidiaLam CombIdToCookieId 那个是不是也可以用CookieID?
> > 
> > 
> > 我的意见还是保留，这个是通过combid查最新cookieid的
> 
> 额？为什么呢？都是ObjectId 吧？ `type CombId = CookieId`

不是诶，combid是70进制的数据源组合id。这个是用combid去查cookieid和updatecookieid出来的意思。

2024-04-15 08:19 UTC, Goodjooy approved these changes

2024-04-15 08:19 UTC, Goodjooy commented on libs/qiniu-manager/examples/delete_mutli_comb.rs
>      }
你这是在写什么东西（
`（1..=2400）.map(|i|format!("{i}.json")).collect::<Vec<_>>()`

2024-04-15 11:36 UTC, merged