✨ 添加腾讯云包，初步搭建prepare和requester
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #190
Opened 2024-06-01 17:00 UTC by phidiaLam

2024-06-07 16:10 UTC, Goodjooy requested changes

2024-06-07 16:10 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/config.rs
> +    fn get_cdn_base_url(&self) -> &str;
base URL建议直接返回URL类型

2024-06-07 16:10 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/requester.rs
> +                }
这些取了option内的值，用if let是否更好？

if let Some(ref _)

2024-06-07 16:10 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/requester.rs
> +    pub(crate) payload: Vec<u8>,
这里加上个fixme吧，使用基于泛型的接口绑定

2024-06-07 16:38 UTC, phidiaLam commented on middle-server/tencent-cloud-server/src/common_parameters.rs
> +    pub algorithm: String,
主要感觉可能也要能支持传递更改？还是没必要

2024-06-07 16:42 UTC, phidiaLam commented on middle-server/tencent-cloud-server/src/common_parameters.rs
> +        let date = datetime.format("%Y-%m-%d").to_string();
下面hmacsha256也要

2024-06-07 16:44 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/common_parameters.rs
> +    pub algorithm: String,
那也能用static str啊

2024-06-08 09:54 UTC, Goodjooy requested changes

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/common_parameters.rs
> +        let host = format!("{}.tencentcloudapi.com", common_params.service);
请求时也会构造host,这里能否构造后缓存或者返回？
比如在manager里面加一个 host: Option<String> 或者将这个host返回

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/common_parameters.rs
> +        let payload_text = serde_json::to_string(&request.payload)?;
这里同上面的host

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/common_parameters.rs
> +        let host = format!("{}.tencentcloudapi.com", common_params.service);
对了，这里建议直接合成URL然后后面用的时候取host,请求时取url

参考：
- [URL::host_str](https://docs.rs/url/latest/url/struct.Url.html#method.host_str)

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/requester.rs
> +    pub(crate) host: String,
这个Host可以通过Url获得，不需要重复传递

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/common_parameters.rs
> +            .token(common_params.token.clone())
后面这些变量在后续requester传递时只使用引用， 因此考虑直接传递引用而不是clone
生命周期长度不超过CloudManager即可，可以使用相同长度的生命周期标记，由于Requester不返回，这个生命周期标记应该可以自动推导。

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/common_parameters.rs
> +        println!("{}", String::from_utf8_lossy(&payload));
使用tracing::debug！

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/requester.rs
> +                );
这些似乎是直接透传的，在这里parser且unwrap感觉不妥，如果是直接透传的对象，在`CommonParameter`构造时就转换为HeaderValue 或者使用枚举类型来限定并提供const的HostValue

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/requester.rs
> +                );
这个同上，此外，content type限制为[`mime::Mime`](https://docs.rs/mime/0.3.17/mime/struct.Mime.html)是否更好？

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/requester.rs
> +    pub(crate) payload: Vec<u8>,
这边的query和payload是互斥的吗？

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/axum_starter.rs
> +        Arc::new(config.get_cdn_base_url().to_string()),
进来都是URL，还转换回String干什么？

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/cdn/purge_urls_cache.rs
> +            .map(|path| format!("{}{}", self.cdn_base_url, path))
这里使用URL的方法来设置Path，可以使用 https://docs.rs/url/latest/url/struct.Url.html#method.options 来构造基于BaseURL的路径设置。后面collect可以考虑https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.try_fold 来实现，并进行预分配内存

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/cloud_manager.rs
> +}
为了避免歧义，建议改成类似 TencentCloudManager的名称

2024-06-08 09:54 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/common_parameters.rs
> +            .token(common_params.token.clone())
如果这些都是字符串字面量，那使用枚举或者const值是一个更好的方式，也便于查找有哪些可供使用的参数

2024-06-09 16:43 UTC, Goodjooy approved these changes

2024-06-09 16:52 UTC, merged