Feat/typed tencent cloud
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #198
Opened 2024-06-12 04:52 UTC by Goodjooy

2024-06-12 08:42 UTC, phidiaLam requested changes

2024-06-12 08:42 UTC, phidiaLam commented on middle-server/tencent-cloud-server/src/cloud_manager/exec_request.rs
> +            .task(task)
怎么感觉task有点点意义不明确，task里面有payload 有query。但是这边payload又被取出来重新构造了

2024-06-12 10:29 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/cloud_manager/entities.rs
> +
对，删了

2024-06-12 10:30 UTC, Goodjooy commented on middle-server/tencent-cloud-server/src/cloud_manager/exec_request.rs
> +            .task(task)
现在调整为使用new构造函数构造

2024-06-12 10:49 UTC, phidiaLam approved these changes

2024-06-13 14:16 UTC, phidiaLam approved these changes

2024-06-16 16:28 UTC, merged