统一版本接口
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #200
Opened 2024-07-04 10:58 UTC by Goodjooy

统一版本接口
- [ ] 设计统一版本接口结构体
  - [ ] 新旧类型转换
- [ ] 旧类型弃用
- [ ] 版本迁移postprepare
- [ ] 统一版本接口设计
- [ ] 旧接口弃用

2024-07-31 13:00 UTC, phidiaLam commented on src/serves/frontend/ceobe/operation/version/controllers.rs
> +    pub async fn release_version(
这个写到cdn下面，要上腾讯云cdn，然后接一下之前写刷新cdn的接口在逻辑层那些改动的地方

2024-08-01 10:36 UTC, phidiaLam requested changes

2024-08-01 10:36 UTC, phidiaLam commented on persistence/dao/ceobe-operate/src/mongo/plugin_version/mod.rs
> +        SuperOperate::child(self)
这边是为什么要改成这样子写

2024-08-02 03:26 UTC, phidiaLam requested changes

2024-08-02 03:26 UTC, phidiaLam commented on persistence/models/mongo-models/src/ceobe/operation/version/models/platform.rs
> +    Edge,
这边还得加一个叫"其他浏览器"，这些是只有zip安装到时候

2024-08-02 03:26 UTC, phidiaLam commented on persistence/dao/ceobe-operate/src/mongo/release_version/retrieve.rs
> +        };
这边改成“_id”可能更好点？nature就是原本mongo文件顺序

2024-08-02 03:26 UTC, phidiaLam commented on persistence/dao/ceobe-operate/src/mongo/release_version/create.rs
> +        }
这部分是不是写到verify

2024-08-02 03:26 UTC, phidiaLam commented on persistence/dao/ceobe-operate/src/mongo/release_version/mod.rs
这边可能还要支持一下update，update支持新表就够了。还有个日志列表，去包含版本、更新内容、平台这些信息，给后端做分页表格查询用，也给前端展示历史更新用

2024-08-02 03:26 UTC, phidiaLam commented on persistence/models/mongo-models/src/ceobe/operation/version/models/conv.rs
> +                ["Chrome", "Edge", "FireFox"]
加两个字，商店

2024-08-02 03:26 UTC, phidiaLam commented on persistence/models/mongo-models/src/ceobe/operation/version/models/conv.rs
> +                    .name("ZIP")
加三个字，包下载其他一样

2024-08-02 03:27 UTC, phidiaLam requested changes
然后缺少后台的统一的create update read delete的http接口

2024-08-09 04:04 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/release_version/retrieve.rs
> +        };
_id 是和时间相关的吗？如果是那也行

2024-08-09 04:05 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/release_version/mod.rs
update delete是声明意思？
- 什么是表新？
- 日志列表就是全部历史版本？

2024-08-25 08:24 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/release_version/mod.rs
我是觉得版本发布后除了删除就不要有别的修改选项了吧？

2024-08-25 08:38 UTC, Goodjooy commented on persistence/models/mongo-models/src/ceobe/operation/version/models/conv.rs
> +                ["Chrome", "Edge", "FireFox"]
为什么叫商店啊，firefox 直接就叫add-ons

2024-08-25 08:46 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/release_version/retrieve.rs
> +        };
这边没区别不改也行吧？

2024-08-25 08:46 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/plugin_version/mod.rs
> +        SuperOperate::child(self)
正常trait调用就是应该这样的，要不可能调用到成员函数

2024-09-05 16:13 UTC, phidiaLam commented on persistence/dao/ceobe-operate/src/mongo/release_version/retrieve.rs
> +        };
会更稳一点

2024-09-05 16:23 UTC, phidiaLam commented on http_service/ceobe_operation/release_version_service/src/handlers/admin_end.rs
>          Ok(ret)
为什么分页总数是单独接口

2024-09-30 16:25 UTC, phidiaLam commented on libs/serve_utils/src/view_traits.rs
> +use serde::{Deserialize, Deserializer, Serialize, Serializer};
包装这个文件是做什么的

2024-09-30 16:25 UTC, phidiaLam commented on macros/status-err-derive/src/lib.rs
> +
这是为啥要加这个

2024-09-30 16:25 UTC, phidiaLam commented on persistence/models/mongo-models/src/ceobe/user_property/models/mod.rs
> +#[allow(clippy::duplicated_attributes)]
这边是什么attribute重复要加这个

2024-09-30 16:25 UTC, phidiaLam commented on src/router/cdn/operation/mod.rs
> +        .nest_controller(ReleaseVersionController, CDN)
有一说一，感觉这个加法还挺奇怪，是不是应该怎么样标记过这整个router是CDN的，然后把ReleaseVersionController加进来的时候就默认用的是CDN的

2024-10-11 15:47 UTC, phidiaLam requested changes

2024-10-11 15:47 UTC, phidiaLam commented on http_service/ceobe_operation/release_version_service/src/handlers.rs
> +    const BASE_URI: &'static str = "/release_version";
我记得我们之前网址全是小驼峰？一般网址没用蛇形

2024-10-11 15:47 UTC, phidiaLam commented on http_service/ceobe_operation/release_version_service/src/handlers.rs
> +            .route("/modify", post(Self::modify_description))
yank叫delete吧，软删除也是删除。通俗易懂点
modify改delete吧，跟以前统一

2024-10-11 15:47 UTC, phidiaLam commented on http_service/ceobe_operation/release_version_service/src/handlers.rs
> +        Router::new().route("/fetch", get(Self::release_version))
这边one或者get？

2024-10-11 15:47 UTC, phidiaLam commented on http_service/ceobe_operation/release_version_service/src/handlers/admin_end.rs
> +        }): MapRejecter<Json<QueryVersionUpdate>>,
这边结构跟create保持一致，不然前端要重写表单

2024-10-11 15:47 UTC, phidiaLam commented on libs/serve_utils/src/view_traits.rs
> +use serde::{Deserialize, Deserializer, Serialize, Serializer};
这个文件把注释加了吧，感觉看懂了又感觉没看懂

2024-10-11 15:47 UTC, phidiaLam commented on logic/ceobe_operation_logic/src/release_version/implement.rs
> +    }
这个不用写吧，直接上面all的时候直接调用两个dao获取

2024-10-11 15:47 UTC, phidiaLam commented on logic/ceobe_operation_logic/src/release_version/implement.rs
> +            .await?;
为什么不是一次性改掉？

2024-10-11 15:47 UTC, phidiaLam commented on persistence/dao/ceobe-operate/src/mongo/release_version/retrieve.rs
> +        };
这边其实最应该还是直接比版本

2024-10-11 15:47 UTC, phidiaLam commented on persistence/dao/ceobe-operate/src/mongo/release_version/update.rs
> +        Ok(())
跟逻辑层说的一样，一次性改掉了，不要分一个个字段改

2024-10-11 15:47 UTC, phidiaLam commented on persistence/dao/ceobe-operate/src/mongo/release_version/delete.rs
> +                            "yanked": true
yanked统一改成deleted吧，差了一下这个英文单词，意思不太对

2024-10-11 15:47 UTC, phidiaLam commented on persistence/dao/ceobe-operate/src/mongo/release_version/verify.rs
> +    // 找到当前平台的最新的发布版本，与当前添加版本比较。新版本必须更新
这是什么意思？这在验证什么有点没看懂

2024-10-11 15:51 UTC, phidiaLam commented on persistence/models/mongo-models/src/ceobe/operation/version/models/platform.rs
> +    Edge,
这个没加吗

2024-10-11 16:05 UTC, phidiaLam requested changes

2024-10-11 16:05 UTC, phidiaLam commented on persistence/models/mongo-models/src/ceobe/operation/version/models/conv.rs
> +                ["Chrome", "Edge", "FireFox"]
这边是要显示在哪里来着，什么字段

2024-10-14 00:44 UTC, Goodjooy commented on macros/status-err-derive/src/lib.rs
> +
你问我干啥，问clippy 啊，宏生成代码触发clippy了

2024-10-29 02:36 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/release_version/retrieve.rs
> +        };
这里版本是字符串格式的，直接字符串比较要对齐版本号中的"."

2024-10-29 02:43 UTC, phidiaLam commented on persistence/dao/ceobe-operate/src/mongo/release_version/retrieve.rs
> +        };
那算了，不然等等3.11<3.8

2024-10-29 03:09 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/release_version/verify.rs
> +    // 找到当前平台的最新的发布版本，与当前添加版本比较。新版本必须更新
新的版本必须大于全部已有版本

2024-10-29 03:09 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/release_version/delete.rs
> +                            "yanked": true
扯回一个版本

2024-10-30 06:33 UTC, Goodjooy commented on persistence/models/mongo-models/src/ceobe/operation/version/models/conv.rs
> +                ["Chrome", "Edge", "FireFox"]
这个是下载链接的部分的显示内容
和 ZIP包下载、云盘备份同级别的

2024-11-05 15:27 UTC, phidiaLam approved these changes

2024-11-05 15:29 UTC, merged