增加 tool_link 的 crud
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #201
Opened 2024-07-06 18:39 UTC by HessTina-YuI

2024-07-24 03:37 UTC, Goodjooy requested changes

2024-07-24 03:37 UTC, Goodjooy commented on persistence/models/mongo-models/src/ceobe/operation/tool_link/check/tool_link_checker.rs
> +}
bson::uuid 有实现Deserialize ,可以直接用反序列化来实现校验
https://docs.rs/bson/latest/bson/uuid/struct.Uuid.html#impl-DeserializeAs%3C'de,+Uuid%3E-for-Uuid

此外，请确保该Checker行为符合预测：如果未提供Id，就生成一个新的，否则进行解析

2024-07-24 03:37 UTC, Goodjooy commented on persistence/models/mongo-models/src/ceobe/operation/tool_link/check/tool_link_checker.rs
> +}
如果只需要引用就能对参数进行校验，可以考虑使用`RefChecker`

此外，URL本身实现了序列化与反序列化，可以不用转换为String再入库。可以直接在URL反序列化过程中处理解析异常

https://docs.rs/url/latest/url/struct.Url.html#impl-Serialize-for-Url
https://docs.rs/url/latest/url/struct.Url.html#impl-Deserialize%3C'de%3E-for-Url

2024-07-24 03:37 UTC, Goodjooy commented on persistence/models/mongo-models/src/ceobe/operation/tool_link/models/mod.rs
> +    pub url: String,
如果是URL的话，均推荐直接使用URL类型来储存

2024-07-24 03:37 UTC, Goodjooy commented on src/router/back_end/ceobe_operation/mod.rs
> +            // .route_layer(AuthorizeLayer::<CeobeTools>::new()),
为何要删除后台管理用户鉴权部分？

2024-07-24 03:37 UTC, Goodjooy commented on src/router/back_end/ceobe_operation/tool_link.rs
> +        .merge(Router::new().nest("/mongo", mongo_tool_link_router()))
为何不直接用`nest` 方法？
https://docs.rs/axum/latest/axum/struct.Router.html#method.nest

2024-07-24 03:37 UTC, Goodjooy commented on src/serves/cdn/ceobe/operation/tool_link/controllers.rs
> +impl CdnOperateToolLinkFrontend {
又有CDN 又有Frontend , 这命名有些问题吧

2024-07-24 03:37 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/tool_link/delete.rs
> +    pub async fn delete(&'db self, id: String) -> OperateResult<()> {
这里可以要求参数直接给定UUID，以避免内部的转换带来的潜在panic

2024-07-24 03:37 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/tool_link/list.rs
> +            .unwrap();
这里使用unwrap的理由？

2024-07-24 03:37 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/tool_link/list.rs
> +        }
这里可以考虑使用`TryStreamExt` 的 `try_collect` 来构造结果

https://docs.rs/futures/latest/futures/stream/trait.TryStreamExt.html#method.try_collect

2024-07-24 03:37 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/tool_link/list.rs
> +            .unwrap();
这里使用unwrap的理由？

2024-07-24 03:37 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/tool_link/mod.rs
> +    pub fn tool_link_mongo(&self) -> ToolLinkOperate<'_, Conn> {
接口名称命名为`tool_link_mongo` 而不是 `tool_link` 的原因？
不同trait的同名函数名是允许的，只是需要注意使用方的trait区分

2024-07-24 03:37 UTC, Goodjooy commented on persistence/dao/ceobe-operate/src/mongo/tool_link/update.rs
> +                        "links": bson::to_bson(&tool_link.links).unwrap(),
建议用模式匹配把`tool_link` 展开，可以简化后续代码

2024-07-24 03:37 UTC, Goodjooy commented on persistence/persistence/src/lib.rs
> +    }
不建议拆分，可以考虑使用 use ... as external_tool_link 来区分，该部分还包含DAO部分的re-export

2024-07-25 07:45 UTC, phidiaLam requested changes

2024-07-25 07:45 UTC, phidiaLam commented on persistence/dao/ceobe-operate/src/mongo/tool_link/list.rs
这边保持curd的r: retrieve，别写list

2024-07-25 07:45 UTC, phidiaLam commented on logic/ceobe_operation_logic/src/view.rs
> +            id: bson::Uuid::new(),
新建的时候符合的

2024-07-25 07:45 UTC, phidiaLam commented on persistence/models/mongo-models/src/ceobe/operation/tool_link/models/mod.rs
> +    pub url: String,
这边主要是写string会少一个model，直接能复用原model

2024-07-25 07:45 UTC, phidiaLam commented on src/router/back_end/ceobe_operation/tool_link.rs
> +        .merge(Router::new().nest("/mongo", mongo_tool_link_router()))
@HessTina-YuI 顺便这边别再套一层mongo吧，直接取一套新名字还是跟这边一致展平吧

2024-07-25 07:45 UTC, phidiaLam commented on src/serves/cdn/ceobe/operation/tool_link/controllers.rs
> +impl CdnOperateToolLinkFrontend {
前台的cdn，没什么毛病

2024-07-25 07:45 UTC, phidiaLam commented on persistence/persistence/src/lib.rs
> +    }
我忘记这边是什么冲突了，你那样可以解决吗

2024-07-25 07:45 UTC, phidiaLam commented on logic/ceobe_operation_logic/src/impletements/tool_link.rs
> +            .await?;
你不是没做分页吗，为什么这边又有page size

2024-07-25 07:45 UTC, phidiaLam commented on logic/ceobe_operation_logic/src/impletements/tool_link.rs
> +            .await?;
如果有做的话，记得前台别做

2024-07-25 07:45 UTC, phidiaLam commented on src/router/back_end/ceobe_operation/mongo/mongo_tool_link.rs
> +        )
这几个要用后台结构体的关联函数，不要写到cdn那边去了

2024-07-25 07:45 UTC, phidiaLam commented on src/serves/cdn/ceobe/operation/tool_link/controllers.rs
> +}
跟router一起换掉，别写cdn这边，写后台那边

2024-07-25 07:45 UTC, phidiaLam commented on src/serves/cdn/ceobe/operation/tool_link/controllers.rs
> +    }
这个也搬到后台，然后前台不分页

2024-08-23 09:28 UTC, Goodjooy commented
@phidiaLam 你看看接口那边命名什么的有没有问题，其他我觉得没啥问题了

2024-08-23 09:31 UTC, Goodjooy approved these changes

2024-08-24 16:18 UTC, phidiaLam approved these changes

2024-08-25 01:05 UTC, merged