后台接口app版本更新
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #58
Opened 2022-08-01 05:12 UTC by phidiaLam

2022-08-03 10:07 UTC, Goodjooy requested changes

2022-08-03 10:07 UTC, Goodjooy commented on models/sql-models/src/ceobe_operation/app_version/operate/create.rs
> +        active.insert(db).await?;
这里需要先进行版本号冲突检查吧？
要不Unique 约束不满足返回的是数据库异常，而不是版本号冲突

2022-08-03 15:11 UTC, phidiaLam commented on models/sql-models/src/ceobe_operation/app_version/operate/create.rs
> +        active.insert(db).await?;
我也是这么想过，但是我考虑的是还要查表一次，浪费。
不过你说的也很有道理，这样子就没办法返回具体信息了，对用户不友好。
明天改

2022-08-03 23:49 UTC, Goodjooy commented on models/sql-models/src/ceobe_operation/app_version/operate/create.rs
> +        active.insert(db).await?;
其实数据库里面unique 约束也是要查表

2022-08-04 03:30 UTC, phidiaLam commented on models/sql-models/src/ceobe_operation/app_version/operate/create.rs
> +        active.insert(db).await?;
插入前查一遍，插入时又查一遍

2022-08-04 04:28 UTC, Goodjooy requested changes

2022-08-04 04:28 UTC, Goodjooy commented on models/sql-models/src/ceobe_operation/app_version/operate/create.rs
> +        }
可以这样
```suggestion
            Err(OperateError::AppVersionIdExist(
                version_info.version,
            ))?;
        }
```

2022-08-04 07:10 UTC, Goodjooy approved these changes

2022-08-04 07:10 UTC, merged