后台用户列表
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #84
Opened 2022-09-27 05:58 UTC by phidiaLam

2022-09-27 08:22 UTC, Goodjooy requested changes

2022-09-27 08:22 UTC, Goodjooy commented on models/sql-models/src/admin_user/operate/retrieve.rs
> +        Ok(user::Entity::find().count(db).await?.try_into().unwrap())
这里是 `usize`  转换为 `u64`

第一，建议直接保留usize , 这个和c/cpp 里面 `size_t` 一样都是表示长度的，钻换为u64 我认为不妥
第二，基本类型转换可以使用 `as`

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        Query(params): Query<HashMap<String, u64>>,
接口缺少数据校验

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        };
如果数据不存在，应该提供报错信息
但是这里会触发panic

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        let resq: ViewUserListResq = ViewUserListResq {
resp
response

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        };
这个最好提供一个关联函数来生成

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +                total_page: (count as f64 / *size as f64).ceil() as u64,
为什么要通过浮点数中转？
直接进行整数除法不行吗？

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        let count = UserSqlOperate::get_user_total_number().await?;
这2 个函数内部分别调用了一次 `get_db_connection`
一定程度上会浪费SQL 连接池

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        AuthorizeInfo(_): AuthorizeInfo,
在不需要用户权限信息时，该参数可用缺省

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        AuthorizeInfo(_): AuthorizeInfo,
同上

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        AuthorizeInfo(_): AuthorizeInfo,
同上

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        >,
没有对请求内容进行校验

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        let new_auth = body.auth;
考虑直接使用模式匹配取得参数

2022-09-27 08:22 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        >,
缺少校验

2022-09-27 08:32 UTC, phidiaLam commented on models/sql-models/src/admin_user/operate/retrieve.rs
> +            .await?)
缓存？缓存是要做什么

2022-09-27 08:33 UTC, Goodjooy commented on models/sql-models/src/admin_user/operate/retrieve.rs
> +            .await?)
翻页算比较高频的行为，每次都去查询数据库吗？

2022-09-27 09:00 UTC, phidiaLam commented on models/sql-models/src/admin_user/operate/retrieve.rs
> +            .await?)
那肯定呀，后台当然不能给缓存，我删除用户或者更改权限都需要重新请求列表，必须保证跟数据库同步

2022-09-27 09:02 UTC, phidiaLam commented on src/serves/backend/user_auth/controllers.rs
> +                total_page: (count as f64 / *size as f64).ceil() as u64,
结果不一定是整数呀，有什么办法可以证书除的时候自动ceil？

2022-09-27 09:02 UTC, phidiaLam commented on src/serves/backend/user_auth/controllers.rs
> +        AuthorizeInfo(_): AuthorizeInfo,
但是要做权限校验，那这个还需要吗

2022-09-27 09:09 UTC, phidiaLam commented on src/serves/backend/user_auth/controllers.rs
> +        >,
那之前改密码什么的那些地方是不是也没有

2022-09-27 09:14 UTC, Goodjooy commented on models/sql-models/src/admin_user/operate/retrieve.rs
> +            .await?)
这是缓存更新策略（）

2022-09-27 09:44 UTC, phidiaLam commented on models/sql-models/src/admin_user/operate/retrieve.rs
> +            .await?)
你指没有缓存时间有etag？后台都没必要吧，后台有用一般都是在变的，后台之前不是统一没有，只在前台做缓存

2022-09-29 12:13 UTC, Goodjooy requested changes

2022-09-29 12:13 UTC, Goodjooy commented on libs/page_size/src/database/mod.rs
> +    fn offset_limit(self, page: usize, size: usize) -> Self;
可以直接传递`PageSize` 而不是拆分传递

2022-10-04 00:09 UTC, Goodjooy requested changes

2022-10-04 00:09 UTC, Goodjooy commented on src/serves/backend/user_auth/controllers.rs
> +        Ok(resq).into()
resp

2022-10-05 11:43 UTC, Goodjooy approved these changes

2022-10-05 11:43 UTC, merged