使用axum-start优化启动
Enraged-Dun-Cookie-Development-Team/Ceobe-Canteen-Serve pull request #89
Opened 2022-10-19 01:14 UTC by phidiaLam

2022-10-19 11:49 UTC, Goodjooy requested changes
0.2.1 已经发布，升级试试把

2022-10-19 11:49 UTC, Goodjooy commented on database/mongo_connection/src/config.rs
> +#[derive(Debug, serde::Deserialize, Clone)]
使用ref 了，这个Clone 就不是必须的拉吧

2022-10-19 11:49 UTC, Goodjooy commented on src/bootstrap/init.rs
> +    (Nest::new("/api/v1", router::root_route()),)
这个括号去掉吧
```suggestion
    Nest::new("/api/v1", router::root_route())
```

2022-10-19 11:49 UTC, Goodjooy commented on src/bootstrap/init.rs
> +    (Fallback::new(not_exist.into_service()),)
这个也一样
```suggestion
    Fallback::new(not_exist.into_service())
```

2022-10-19 11:49 UTC, Goodjooy commented on src/bootstrap/init.rs
> +    SetGraceful::new(rx.map(|_| ()))
这里其实直接把等待ctrlc的信号塞进去似乎也行？
```suggestion
    SetGraceful::new(tokio::signal::ctrl_c().map(|_|{log::info!("收到退出信号");}))
```

2022-10-19 11:49 UTC, Goodjooy commented on src/configs/http_listen_config.rs
> +#[derive(Debug, serde::Deserialize, Clone)]
这个也是

2022-10-19 11:49 UTC, Goodjooy commented on src/configs/mod.rs
> +}
你猜猜 `HttpConfig` 这个trait 是干什么的

`crate::configs::http_listen_config::HttpConfig`

2022-10-19 11:49 UTC, Goodjooy commented on src/main.rs
> +#![allow(clippy::needless_lifetimes)]
升级到 0.2 ，这个东西应该就能去掉了

2022-10-19 11:49 UTC, Goodjooy commented on src/configs/logger.rs
> +#[derive(Debug, Deserialize, Clone)]
这个clone 也不必要了把

2022-10-20 01:19 UTC, phidiaLam commented on src/bootstrap/init.rs
> +#[prepare(BackAuthConfig 'arg)]
这个主要怕前台之后也有鉴权，就命名为后台鉴权了

2022-10-20 01:35 UTC, phidiaLam commented on src/bootstrap/init.rs
> +    SetGraceful::new(rx.map(|_| ()))
可以的

2022-10-20 01:40 UTC, phidiaLam commented on src/bootstrap/init.rs
> +#[prepare(RouterFallback)]
这个不是只用在路由？

2022-10-20 08:30 UTC, Goodjooy approved these changes

2022-10-20 09:22 UTC, merged